version: 2.1

executors:
  java-version:
    docker:
      - image: 'cimg/openjdk:11.0.7'

orbs:
  maven: circleci/maven@1.0.0
  heroku: circleci/heroku@1.0.1

jobs:
  deploy:
    docker:
      - image: circleci/buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name:
            Deploy app on Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  build_deploy:
    jobs:
      - maven/test:
          executor: java-version
      - deploy:
          requires:
            - maven/test
          filters:
            branches:
              only: master

