version: 2.1

executors:
  java-version:
    docker:
      - image: 'cimg/openjdk:11.0.7'

orbs:
  maven: circleci/maven@1.0.0
  heroku: circleci/heroku@1.0.1

workflows:
  maven_test:
    jobs:
      - maven/test

jobs:
  build:
    executor: java-version
    steps:
      - checkout
      - maven/test