version: 2.1

executors:
  java-version:
    docker:
      - image: 'cimg/openjdk:11.0.7'

orbs:
  maven: circleci/maven@1.0.0
  heroku: circleci/heroku@1.0.1

workflows:
  build_deploy:
    jobs:
      - maven/test:
          executor: java-version
          environment:
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
            REGISTRATION_URL: ${REGISTRATION_URL}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: spring.mail.port=${MAIL_PORT}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
      - heroku/deploy-via-git:
          requires:
            - maven/test
          filters:
            branches:
              only: master

