version: 2.1
executors:
  my-executor:
    tag: '11.0'


orbs:
  maven: circleci/maven@1.0.0

workflows:
  maven_test:
    executor: my-executor
    jobs:
      - maven/test # checkout, build, test, and upload test results
