version: 2.1

executors:
  java-version:
    parameters:
      tag: '11.0'

orbs:
  maven: circleci/maven@1.0.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: java-version
