version: 2.1

executors:
  java-version:
    docker:
      - image: 'cimg/openjdk:11.0.7'

orbs:
  maven: circleci/maven@1.0.0

workflows:
  build_deploy:
    jobs:
      - build

jobs:
  build:
    - maven/test:
        executor: java-version