version: 2.1

executors:
  java-version:
    docker:
      - image: 'cimg/openjdk:11.0.7'

orbs:
  maven: circleci/maven@1.0.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: java-version
